### ISSUE TITLE
Wishlist By pgain2004

### ISSUE THREAD

**Issue by pgain2004** [ykrank/S1-Next#1]
Version 0.7.0

Feature:
自动草稿功能：在编辑帖子界面退出时不需要询问“是否放弃编辑内容”，而是直接返回帖子/版块列表，保留既输入内容，留待下次进入该界面继续。对应情景范例：编辑过程中需要返回本帖甚至是其它帖子查看、引用(复制)发言，现版本必须放弃当前所有编辑内容，除非有inputting+/typemachine之类记忆输入内容的辅助应用。
(次要)”我的回复“入口：能进入我的回复，并可在点击相关回复时跳转到该帖子的该楼层。方便同时追踪多个回复。

Bug:
(非必要)一旦Substratum主题替换了滚动条，则无法输入内容并会FC。

**Comment by ykrank** [comment]
草稿功能：
[编辑新帖，回复，私信时会有缓存](https://github.com/ykrank/S1-Next/commit/89f37fed07905b2bc0f33bcb4e1c25a3c967b67a)

**Comment by ykrank** [comment]
Substratum主题：
按照系统规范开发，无法保证和第三方插件的兼容性

**Comment by ykrank** [comment]
我的回复 [user replies in user home ](https://github.com/ykrank/S1-Next/commit/17fcd0e9d6b760c6e5c042d8e10a5f35309602e0)
