### ISSUE TITLE
无法查看个人资料卡

### ISSUE THREAD

**Issue by sky0hjh** [ykrank/S1-Next#12]
查看个人资料卡的时候无法看见除用户uid及昵称外的其他任何信息，像下面这样
![Screenshot_2018-03-07-19-50-58.jpg](https://i.loli.net/2018/03/07/5a9fd24046cd3.jpg)

**Comment by sky0hjh** [comment]
m对了，头像也可以看。。。

**Comment by ykrank** [comment]
直接访问的接口目前被封了，这段时间过去了也许会开放

**Comment by ykrank** [comment]
通过其他方法绕过了
