### ISSUE TITLE
App crashed on weak network connection

### ISSUE THREAD

**Issue by kelthuzad13** [ykrank/S1-Next#17]
看帖翻页拉取数据时，如果碰到弱网/飞行模式等情况，请求超时后会 crash。可能是 RxJava 2 的问题，和这个问题类似。

https://github.com/ReactiveX/RxJava/issues/4807

日志如下， w 和 e 的日志

> 09-30 11:34:03.715 26676-26676/? W/System.err: java.net.UnknownHostException: Unable to resolve host "bbs.saraba1st.com": No address associated with hostname
09-30 11:34:03.715 26676-26676/? W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:440)
09-30 11:34:03.715 26676-26676/? W/System.err:     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
09-30 11:34:03.715 26676-26676/? W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:215)
09-30 11:34:03.715 26676-26676/? W/System.err:     at okhttp3.o$1.a(Proguard:40)
09-30 11:34:03.716 26676-26676/? W/System.err:     at com.github.ykrank.androidtools.widget.b.b.a(Proguard:41)
09-30 11:34:03.716 26676-26676/? W/System.err:     at okhttp3.internal.b.f.a(Proguard:185)
09-30 11:34:03.716 26676-26676/? W/System.err:     at okhttp3.internal.b.f.d(Proguard:149)
09-30 11:34:03.716 26676-26676/? W/System.err:     at okhttp3.internal.b.f.b(Proguard:84)
09-30 11:34:03.716 26676-26676/? W/System.err:     at okhttp3.internal.b.g.a(Proguard:214)
09-30 11:34:03.716 26676-26676/? W/System.err:     at okhttp3.internal.b.g.a(Proguard:135)
09-30 11:34:03.716 26676-26676/? W/System.err:     at okhttp3.internal.b.g.a(Proguard:114)
09-30 11:34:03.716 26676-26676/? W/System.err:     at okhttp3.internal.b.a.a(Proguard:42)
09-30 11:34:03.716 26676-26676/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:147)
09-30 11:34:03.716 26676-26676/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:121)
09-30 11:34:03.716 26676-26676/? W/System.err:     at okhttp3.internal.a.a.a(Proguard:93)
09-30 11:34:03.716 26676-26676/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:147)
09-30 11:34:03.717 26676-28271/? W/System.err: 	at io.a.c.a: 2 exceptions occurred. 
09-30 11:34:03.717 26676-28271/? W/System.err:     at io.a.e.e.c.v$a.onError(Proguard:76)
09-30 11:34:03.717 26676-28271/? W/System.err:     at io.a.e.d.a.onError(Proguard:100)
09-30 11:34:03.717 26676-28271/? W/System.err:     at io.a.e.d.g.b(Proguard:100)
09-30 11:34:03.717 26676-28271/? W/System.err:     at io.a.e.e.d.p$a.a(Proguard:78)
09-30 11:34:03.717 26676-28271/? W/System.err:     at io.a.e.e.c.aa$a.onError(Proguard:95)
09-30 11:34:03.717 26676-28271/? W/System.err:     at d.a.a.a$a.onError(Proguard:72)
09-30 11:34:03.717 26676-28271/? W/System.err:     at d.a.a.c.a(Proguard:56)
09-30 11:34:03.717 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.717 26676-28271/? W/System.err:     at d.a.a.a.a(Proguard:34)
09-30 11:34:03.717 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.717 26676-28271/? W/System.err:     at io.a.e.e.c.aa.a(Proguard:35)
09-30 11:34:03.717 26676-28271/? W/System.err:     at io.a.p.b(Proguard:3313)
09-30 11:34:03.717 26676-28271/? W/System.err:     at io.a.e.e.d.p.a(Proguard:36)
09-30 11:34:03.717 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.717 26676-28271/? W/System.err:     at io.a.e.e.c.t.a(Proguard:33)
09-30 11:34:03.717 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.717 26676-28271/? W/System.err:     at io.a.e.e.c.v.a(Proguard:31)
09-30 11:34:03.717 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.717 26676-28271/? W/System.err:     at io.a.e.e.c.t.a(Proguard:33)
09-30 11:34:03.717 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.717 26676-28271/? W/System.err:     at io.a.e.e.c.e.a(Proguard:39)
09-30 11:34:03.718 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.718 26676-28271/? W/System.err:     at io.a.e.e.c.aa.a(Proguard:35)
09-30 11:34:03.718 26676-28271/? W/System.err:     at io.a.p.b(Proguard:3313)
09-30 11:34:03.718 26676-28271/? W/System.err:     at io.a.e.e.d.h.a(Proguard:36)
09-30 11:34:03.718 26676-28271/? W/System.err:     at io.a.p.b(Proguard:3313)
09-30 11:34:03.718 26676-28271/? W/System.err:     at io.a.e.e.d.o$a.run(Proguard:89)
09-30 11:34:03.718 26676-28271/? W/System.err:     at io.a.o$a.run(Proguard:579)
09-30 11:34:03.718 26676-28271/? W/System.err:     at io.a.e.g.k.run(Proguard:66)
09-30 11:34:03.718 26676-28271/? W/System.err:     at io.a.e.g.k.call(Proguard:57)
09-30 11:34:03.718 26676-28271/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-30 11:34:03.718 26676-28271/? W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
09-30 11:34:03.718 26676-28271/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-30 11:34:03.718 26676-28271/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-30 11:34:03.718 26676-28271/? W/System.err:     at java.lang.Thread.run(Thread.java:818)
09-30 11:34:03.718 26676-28271/? W/System.err:   ComposedException 1 :
09-30 11:34:03.718 26676-28271/? W/System.err: 	java.net.UnknownHostException: Unable to resolve host "bbs.saraba1st.com": No address associated with hostname
09-30 11:34:03.718 26676-28271/? W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:440)
09-30 11:34:03.718 26676-28271/? W/System.err:     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
09-30 11:34:03.718 26676-28271/? W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:215)
09-30 11:34:03.718 26676-28271/? W/System.err:     at okhttp3.o$1.a(Proguard:40)
09-30 11:34:03.718 26676-28271/? W/System.err:     at com.github.ykrank.androidtools.widget.b.b.a(Proguard:41)
09-30 11:34:03.718 26676-28271/? W/System.err:     at okhttp3.internal.b.f.a(Proguard:185)
09-30 11:34:03.718 26676-28271/? W/System.err:     at okhttp3.internal.b.f.d(Proguard:149)
09-30 11:34:03.718 26676-28271/? W/System.err:     at okhttp3.internal.b.f.b(Proguard:84)
09-30 11:34:03.718 26676-28271/? W/System.err:     at okhttp3.internal.b.g.a(Proguard:214)
09-30 11:34:03.718 26676-28271/? W/System.err:     at okhttp3.internal.b.g.a(Proguard:135)
09-30 11:34:03.719 26676-28271/? W/System.err:     at okhttp3.internal.b.g.a(Proguard:114)
09-30 11:34:03.719 26676-28271/? W/System.err:     at okhttp3.internal.b.a.a(Proguard:42)
09-30 11:34:03.719 26676-28271/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:147)
09-30 11:34:03.719 26676-28271/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:121)
09-30 11:34:03.719 26676-28271/? W/System.err:     at okhttp3.internal.a.a.a(Proguard:93)
09-30 11:34:03.719 26676-28271/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:147)
09-30 11:34:03.719 26676-28271/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:121)
09-30 11:34:03.719 26676-28271/? W/System.err:     at okhttp3.internal.c.a.a(Proguard:93)
09-30 11:34:03.719 26676-28271/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:147)
09-30 11:34:03.719 26676-28271/? W/System.err:     at okhttp3.internal.c.j.a(Proguard:126)
09-30 11:34:03.719 26676-28271/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:147)
09-30 11:34:03.719 26676-28271/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:121)
09-30 11:34:03.719 26676-28271/? W/System.err:     at com.github.ykrank.androidtools.widget.b.c.a(Proguard:69)
09-30 11:34:03.719 26676-28271/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:147)
09-30 11:34:03.719 26676-28271/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:121)
09-30 11:34:03.719 26676-28271/? W/System.err:     at me.ykrank.s1next.data.api.f.a(Proguard:31)
09-30 11:34:03.719 26676-28271/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:147)
09-30 11:34:03.719 26676-28271/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:121)
09-30 11:34:03.719 26676-28271/? W/System.err:     at okhttp3.aa.g(Proguard:200)
09-30 11:34:03.719 26676-28271/? W/System.err:     at okhttp3.aa.a(Proguard:77)
09-30 11:34:03.719 26676-28271/? W/System.err:     at d.i.a(Proguard:180)
09-30 11:34:03.719 26676-28271/? W/System.err:     at d.a.a.c.a(Proguard:42)
09-30 11:34:03.719 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.720 26676-28271/? W/System.err:     at d.a.a.a.a(Proguard:34)
09-30 11:34:03.720 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.720 26676-28271/? W/System.err:     at io.a.e.e.c.aa.a(Proguard:35)
09-30 11:34:03.720 26676-28271/? W/System.err:     at io.a.p.b(Proguard:3313)
09-30 11:34:03.720 26676-28271/? W/System.err:     at io.a.e.e.d.p.a(Proguard:36)
09-30 11:34:03.720 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.720 26676-28271/? W/System.err:     at io.a.e.e.c.t.a(Proguard:33)
09-30 11:34:03.720 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.720 26676-28271/? W/System.err:     at io.a.e.e.c.v.a(Proguard:31)
09-30 11:34:03.720 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.720 26676-28271/? W/System.err:     at io.a.e.e.c.t.a(Proguard:33)
09-30 11:34:03.720 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.720 26676-28271/? W/System.err:     at io.a.e.e.c.e.a(Proguard:39)
09-30 11:34:03.720 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.720 26676-28271/? W/System.err:     at io.a.e.e.c.aa.a(Proguard:35)
09-30 11:34:03.720 26676-28271/? W/System.err:     at io.a.p.b(Proguard:3313)
09-30 11:34:03.720 26676-28271/? W/System.err:     at io.a.e.e.d.h.a(Proguard:36)
09-30 11:34:03.720 26676-28271/? W/System.err:     at io.a.p.b(Proguard:3313)
09-30 11:34:03.720 26676-28271/? W/System.err:     at io.a.e.e.d.o$a.run(Proguard:89)
09-30 11:34:03.721 26676-28271/? W/System.err:     at io.a.o$a.run(Proguard:579)
09-30 11:34:03.721 26676-28271/? W/System.err:     at io.a.e.g.k.run(Proguard:66)
09-30 11:34:03.721 26676-28271/? W/System.err:     at io.a.e.g.k.call(Proguard:57)
09-30 11:34:03.721 26676-28271/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-30 11:34:03.721 26676-28271/? W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
09-30 11:34:03.721 26676-28271/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-30 11:34:03.721 26676-28271/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-30 11:34:03.721 26676-28271/? W/System.err:     at java.lang.Thread.run(Thread.java:818)
09-30 11:34:03.721 26676-28271/? W/System.err:   ComposedException 2 :
09-30 11:34:03.721 26676-28271/? W/System.err: 	io.rx_cache2.o: The Loader provided did not return any data and there is not data to load from the Cache posts_wrapper_new
09-30 11:34:03.721 26676-28271/? W/System.err:     at io.rx_cache2.internal.g$5.apply(Proguard:148)
09-30 11:34:03.721 26676-28271/? W/System.err:     at io.a.e.e.c.v$a.onError(Proguard:73)
09-30 11:34:03.721 26676-28271/? W/System.err:     at io.a.e.d.a.onError(Proguard:100)
09-30 11:34:03.721 26676-28271/? W/System.err:     at io.a.e.d.g.b(Proguard:100)
09-30 11:34:03.721 26676-28271/? W/System.err:     at io.a.e.e.d.p$a.a(Proguard:78)
09-30 11:34:03.721 26676-28271/? W/System.err:     at io.a.e.e.c.aa$a.onError(Proguard:95)
09-30 11:34:03.721 26676-28271/? W/System.err:     at d.a.a.a$a.onError(Proguard:72)
09-30 11:34:03.721 26676-28271/? W/System.err:     at d.a.a.c.a(Proguard:56)
09-30 11:34:03.721 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.721 26676-28271/? W/System.err:     at d.a.a.a.a(Proguard:34)
09-30 11:34:03.721 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.722 26676-28271/? W/System.err:     at io.a.e.e.c.aa.a(Proguard:35)
09-30 11:34:03.722 26676-28271/? W/System.err:     at io.a.p.b(Proguard:3313)
09-30 11:34:03.722 26676-28271/? W/System.err:     at io.a.e.e.d.p.a(Proguard:36)
09-30 11:34:03.722 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.722 26676-28271/? W/System.err:     at io.a.e.e.c.t.a(Proguard:33)
09-30 11:34:03.722 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.722 26676-28271/? W/System.err:     at io.a.e.e.c.v.a(Proguard:31)
09-30 11:34:03.722 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.722 26676-28271/? W/System.err:     at io.a.e.e.c.t.a(Proguard:33)
09-30 11:34:03.722 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.722 26676-28271/? W/System.err:     at io.a.e.e.c.e.a(Proguard:39)
09-30 11:34:03.722 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.722 26676-28271/? W/System.err:     at io.a.e.e.c.aa.a(Proguard:35)
09-30 11:34:03.722 26676-28271/? W/System.err:     at io.a.p.b(Proguard:3313)
09-30 11:34:03.722 26676-28271/? W/System.err:     at io.a.e.e.d.h.a(Proguard:36)
09-30 11:34:03.722 26676-28271/? W/System.err:     at io.a.p.b(Proguard:3313)
09-30 11:34:03.722 26676-28271/? W/System.err:     at io.a.e.e.d.o$a.run(Proguard:89)
09-30 11:34:03.722 26676-28271/? W/System.err:     at io.a.o$a.run(Proguard:579)
09-30 11:34:03.722 26676-28271/? W/System.err:     at io.a.e.g.k.run(Proguard:66)
09-30 11:34:03.722 26676-28271/? W/System.err:     at io.a.e.g.k.call(Proguard:57)
09-30 11:34:03.722 26676-28271/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-30 11:34:03.723 26676-28271/? W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
09-30 11:34:03.723 26676-28271/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-30 11:34:03.723 26676-28271/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-30 11:34:03.723 26676-28271/? W/System.err:     at java.lang.Thread.run(Thread.java:818)
09-30 11:34:03.723 26676-28271/? W/System.err: 	Caused by: java.net.UnknownHostException: Unable to resolve host "bbs.saraba1st.com": No address associated with hostname
09-30 11:34:03.723 26676-28271/? W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:440)
09-30 11:34:03.723 26676-28271/? W/System.err:     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
09-30 11:34:03.723 26676-28271/? W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:215)
09-30 11:34:03.723 26676-28271/? W/System.err:     at okhttp3.o$1.a(Proguard:40)
09-30 11:34:03.723 26676-28271/? W/System.err:     at com.github.ykrank.androidtools.widget.b.b.a(Proguard:41)
09-30 11:34:03.723 26676-28271/? W/System.err:     at okhttp3.internal.b.f.a(Proguard:185)
09-30 11:34:03.723 26676-28271/? W/System.err:     at okhttp3.internal.b.f.d(Proguard:149)
09-30 11:34:03.723 26676-28271/? W/System.err:     at okhttp3.internal.b.f.b(Proguard:84)
09-30 11:34:03.723 26676-28271/? W/System.err:     at okhttp3.internal.b.g.a(Proguard:214)
09-30 11:34:03.723 26676-28271/? W/System.err:     at okhttp3.internal.b.g.a(Proguard:135)
09-30 11:34:03.723 26676-28271/? W/System.err:     at okhttp3.internal.b.g.a(Proguard:114)
09-30 11:34:03.723 26676-28271/? W/System.err:     at okhttp3.internal.b.a.a(Proguard:42)
09-30 11:34:03.723 26676-28271/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:147)
09-30 11:34:03.723 26676-28271/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:121)
09-30 11:34:03.724 26676-28271/? W/System.err:     at okhttp3.internal.a.a.a(Proguard:93)
09-30 11:34:03.724 26676-28271/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:147)
09-30 11:34:03.724 26676-28271/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:121)
09-30 11:34:03.724 26676-28271/? W/System.err:     at okhttp3.internal.c.a.a(Proguard:93)
09-30 11:34:03.724 26676-28271/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:147)
09-30 11:34:03.724 26676-28271/? W/System.err:     at okhttp3.internal.c.j.a(Proguard:126)
09-30 11:34:03.724 26676-28271/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:147)
09-30 11:34:03.724 26676-28271/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:121)
09-30 11:34:03.724 26676-28271/? W/System.err:     at com.github.ykrank.androidtools.widget.b.c.a(Proguard:69)
09-30 11:34:03.724 26676-28271/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:147)
09-30 11:34:03.724 26676-28271/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:121)
09-30 11:34:03.724 26676-28271/? W/System.err:     at me.ykrank.s1next.data.api.f.a(Proguard:31)
09-30 11:34:03.724 26676-28271/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:147)
09-30 11:34:03.724 26676-28271/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:121)
09-30 11:34:03.724 26676-28271/? W/System.err:     at okhttp3.aa.g(Proguard:200)
09-30 11:34:03.724 26676-28271/? W/System.err:     at okhttp3.aa.a(Proguard:77)
09-30 11:34:03.724 26676-28271/? W/System.err:     at d.i.a(Proguard:180)
09-30 11:34:03.724 26676-28271/? W/System.err:     at d.a.a.c.a(Proguard:42)
09-30 11:34:03.724 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.724 26676-28271/? W/System.err:     at d.a.a.a.a(Proguard:34)
09-30 11:34:03.724 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.725 26676-28271/? W/System.err:     at io.a.e.e.c.aa.a(Proguard:35)
09-30 11:34:03.725 26676-28271/? W/System.err:     at io.a.p.b(Proguard:3313)
09-30 11:34:03.725 26676-28271/? W/System.err:     at io.a.e.e.d.p.a(Proguard:36)
09-30 11:34:03.725 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.725 26676-28271/? W/System.err:     at io.a.e.e.c.t.a(Proguard:33)
09-30 11:34:03.725 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.725 26676-28271/? W/System.err:     at io.a.e.e.c.v.a(Proguard:31)
09-30 11:34:03.725 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.725 26676-28271/? W/System.err:     at io.a.e.e.c.t.a(Proguard:33)
09-30 11:34:03.725 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.725 26676-28271/? W/System.err:     at io.a.e.e.c.e.a(Proguard:39)
09-30 11:34:03.725 26676-28271/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.725 26676-28271/? W/System.err:     at io.a.e.e.c.aa.a(Proguard:35)
09-30 11:34:03.725 26676-28271/? W/System.err:     at io.a.p.b(Proguard:3313)
09-30 11:34:03.725 26676-28271/? W/System.err:     at io.a.e.e.d.h.a(Proguard:36)
09-30 11:34:03.725 26676-28271/? W/System.err:     at io.a.p.b(Proguard:3313)
09-30 11:34:03.725 26676-28271/? W/System.err:     at io.a.e.e.d.o$a.run(Proguard:89)
09-30 11:34:03.725 26676-28271/? W/System.err:     at io.a.o$a.run(Proguard:579)
09-30 11:34:03.725 26676-28271/? W/System.err:     at io.a.e.g.k.run(Proguard:66)
09-30 11:34:03.726 26676-28271/? W/System.err:     at io.a.e.g.k.call(Proguard:57)
09-30 11:34:03.726 26676-28271/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-30 11:34:03.726 26676-28271/? W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
09-30 11:34:03.726 26676-28271/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-30 11:34:03.726 26676-28271/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-30 11:34:03.726 26676-28271/? W/System.err:     at java.lang.Thread.run(Thread.java:818)
09-30 11:34:03.726 26676-26676/? W/System.err: okhttp3.internal.c.g.a(Proguard:121)
09-30 11:34:03.726 26676-26676/? W/System.err:     at okhttp3.internal.c.a.a(Proguard:93)
09-30 11:34:03.726 26676-26676/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:147)
09-30 11:34:03.726 26676-26676/? W/System.err:     at okhttp3.internal.c.j.a(Proguard:126)
09-30 11:34:03.726 26676-26676/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:147)
09-30 11:34:03.726 26676-26676/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:121)
09-30 11:34:03.727 26676-26676/? W/System.err:     at com.github.ykrank.androidtools.widget.b.c.a(Proguard:69)
09-30 11:34:03.727 26676-26676/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:147)
09-30 11:34:03.727 26676-26676/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:121)
09-30 11:34:03.727 26676-26676/? W/System.err:     at me.ykrank.s1next.data.api.f.a(Proguard:31)
09-30 11:34:03.727 26676-26676/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:147)
09-30 11:34:03.727 26676-26676/? W/System.err:     at okhttp3.internal.c.g.a(Proguard:121)
09-30 11:34:03.727 26676-26676/? W/System.err:     at okhttp3.aa.g(Proguard:200)
09-30 11:34:03.727 26676-26676/? W/System.err:     at okhttp3.aa.a(Proguard:77)
09-30 11:34:03.727 26676-26676/? W/System.err:     at d.i.a(Proguard:180)
09-30 11:34:03.727 26676-26676/? W/System.err:     at d.a.a.c.a(Proguard:42)
09-30 11:34:03.727 26676-26676/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.727 26676-26676/? W/System.err:     at d.a.a.a.a(Proguard:34)
09-30 11:34:03.727 26676-26676/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.727 26676-26676/? W/System.err:     at io.a.e.e.c.aa.a(Proguard:35)
09-30 11:34:03.727 26676-26676/? W/System.err:     at io.a.p.b(Proguard:3313)
09-30 11:34:03.728 26676-26676/? W/System.err:     at io.a.e.e.d.p.a(Proguard:36)
09-30 11:34:03.728 26676-26676/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.728 26676-26676/? W/System.err:     at io.a.e.e.c.t.a(Proguard:33)
09-30 11:34:03.728 26676-26676/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.728 26676-26676/? W/System.err:     at io.a.e.e.c.v.a(Proguard:31)
09-30 11:34:03.728 26676-26676/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.728 26676-26676/? W/System.err:     at io.a.e.e.c.t.a(Proguard:33)
09-30 11:34:03.728 26676-26676/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.728 26676-26676/? W/System.err:     at io.a.e.e.c.e.a(Proguard:39)
09-30 11:34:03.728 26676-26676/? W/System.err:     at io.a.i.b(Proguard:12036)
09-30 11:34:03.728 26676-26676/? W/System.err:     at io.a.e.e.c.aa.a(Proguard:35)
09-30 11:34:03.728 26676-26676/? W/System.err:     at io.a.p.b(Proguard:3313)
09-30 11:34:03.728 26676-26676/? W/System.err:     at io.a.e.e.d.h.a(Proguard:36)
09-30 11:34:03.729 26676-26676/? W/System.err:     at io.a.p.b(Proguard:3313)
09-30 11:34:03.729 26676-26676/? W/System.err:     at io.a.e.e.d.o$a.run(Proguard:89)
09-30 11:34:03.729 26676-26676/? W/System.err:     at io.a.o$a.run(Proguard:579)
09-30 11:34:03.729 26676-26676/? W/System.err:     at io.a.e.g.k.run(Proguard:66)
09-30 11:34:03.729 26676-26676/? W/System.err:     at io.a.e.g.k.call(Proguard:57)
09-30 11:34:03.729 26676-26676/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-30 11:34:03.729 26676-26676/? W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
09-30 11:34:03.729 26676-26676/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-30 11:34:03.729 26676-26676/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-30 11:34:03.729 26676-26676/? W/System.err:     at java.lang.Thread.run(Thread.java:818)
09-30 11:34:03.729 26676-26676/? W/System.err: Caused by: java.lang.RuntimeException: Duplicate found in causal chain so cropping to prevent loop ...
09-30 11:34:03.730 26676-26676/? W/System.err:     at me.ykrank.s1next.d.e.a(Proguard:20)
09-30 11:34:03.730 26676-26676/? W/System.err:     at com.github.ykrank.androidtools.f.e.a(Proguard:312)
09-30 11:34:03.730 26676-26676/? W/System.err:     at me.ykrank.s1next.view.fragment.PostListPagerFragment.a(Proguard:434)
09-30 11:34:03.730 26676-26676/? W/System.err:     at com.github.ykrank.androidtools.f.e$d.a(Proguard:263)
09-30 11:34:03.730 26676-26676/? W/System.err:     at com.github.ykrank.androidtools.f.e$d.accept(Proguard:34)
09-30 11:34:03.730 26676-26676/? W/System.err:     at io.a.e.d.f.a(Proguard:47)
09-30 11:34:03.730 26676-26676/? W/System.err:     at io.a.e.e.d.c$a.a(Proguard:77)
09-30 11:34:03.730 26676-26676/? W/System.err:     at io.a.e.e.d.n$a.run(Proguard:79)
09-30 11:34:03.730 26676-26676/? W/System.err:     at io.a.a.b.b$b.run(Proguard:109)
09-30 11:34:03.730 26676-26676/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
09-30 11:34:03.730 26676-26676/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
09-30 11:34:03.730 26676-26676/? W/System.err:     at android.os.Looper.loop(Looper.java:148)
09-30 11:34:03.730 26676-26676/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
09-30 11:34:03.730 26676-26676/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-30 11:34:03.730 26676-26676/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-30 11:34:03.731 26676-26676/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-30 11:34:03.731 26676-26676/? W/System.err:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)    
 --------- beginning of crash
09-30 11:34:03.978 26676-28271/? E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-17
    Process: me.ykrank.s1next, PID: 26676
09-30 11:34:03.990 5418-7919/? W/ActivityManager:   Force finishing activity me.ykrank.s1next/.view.activity.PostListActivity

**Comment by ykrank** [comment]
这个我也注意到了，其实是RxCache的bug，暂时通过添加全局的错误处理规避了
