### ISSUE TITLE
BUG 调整字体大小

### ISSUE THREAD

**Issue by yiranshenqi** [ykrank/S1-Next#2]
0.6.2以后的版本
调整字体大小只在首页起作用，帖子列表和内容无变化。
sony z2 l50t 4.4.2

**Comment by ykrank** [comment]
测试了一下，的确5.0之前的Android会存在这样的问题

**Comment by ykrank** [comment]
[Issue2](https://github.com/ykrank/S1-Next/commit/2843a0b14a1a8341162ddd8f63db81ff1e372e8c)
Fixed
