### ISSUE TITLE
图片加载与文字重叠问题

### ISSUE THREAD

**Issue by iamcxds** [ykrank/S1-Next#28]
打开有图片在文字上面的或者多张图片的，会出现重叠的情况
![Screenshot_2020-03-15-23-56-55-247_me ykrank s1next](https://user-images.githubusercontent.com/10074835/76712432-49e7e900-6719-11ea-9751-394ed52f566b.jpg)

**Comment by lersh** [comment]
我也有这个问题，图文混排的帖子，文字和图片层叠的问题非常严重。

**Comment by ykrank** [comment]
关闭可复制，使用浏览模式就没这问题。
