### ISSUE TITLE
AMOLED黑主题下部分帖子黑字不可阅读

### ISSUE THREAD

**Issue by borisx** [ykrank/S1-Next#3]
有没有可能加个无视字体样式的功能，或者单独针对黑色深灰色进行一下调整

**Comment by ykrank** [comment]
有没有具体的帖子ID可以看一下效果？

**Comment by borisx** [comment]
http://bbs.saraba1st.com/2b/thread-1357558-0-1.html
字全黑的情况
http://bbs.saraba1st.com/2b/thread-1357587-0-1.html
字深灰很难阅读的情况

**Comment by ykrank** [comment]
看了下，原因是因为帖子强制指定了颜色。这种情况下可以认为发帖者是故意这么设置的。就像有些帖子故意设成浅黄色来隐藏一样，并没有什么必要修改。如果遇到这种情况，你可以选择左侧边缘右划，可以直接在侧边栏修改主题
