### ISSUE TITLE
在Android 12上，上传图片功能无效

### ISSUE THREAD

**Issue by ipcjs** [ykrank/S1-Next#31]
（仓库里没最新的代码，我解不了🥲）
只授权了媒体权限的情况下，相册列表显示不出来，一直转圈，如下图所示。

![Screenshot_20220211-044904](https://user-images.githubusercontent.com/4396864/153494237-26f9c449-7fc7-45cd-8dec-c0afd79e9471.png)

环境：
- Google Pixel 6 Pro 
- Android 12
- v2.5.2-play

**Comment by ykrank** [comment]
已更新到最新代码

**Comment by yiranshenqi** [comment]
好像商店没更新？

**Comment by anaizy31** [comment]
我也遇到了同样的问题
环境为 ONEPLUS 6, Android 11 OxygenOS 11.1.2.2, 2.5.2-play
