### ISSUE TITLE
搬运群文件中的2.5.4版本下载

### ISSUE THREAD

**Issue by TomoeMami** [ykrank/S1-Next#36]
https://github.com/TomoeMami/S1PlainTextBackup/releases/tag/Other1

搬运群文件中的最新版本2.5.4下载于另一个repo的release中

**Comment by ipcjs** [comment]
啥意思？最新的就是这个版本呀🤔

**Comment by TomoeMami** [comment]
有人说github上找不到最新版的下载，Google Play里又是2.5.2，酷安也找不到，所以搬运了下群里的文件。

最好是直接更新这边的release就是。

**Comment by ipcjs** [comment]
哦，不过，下老版，应该会提示升级成最新版的吧
