### ISSUE TITLE
gif图片会花

### ISSUE THREAD

**Issue by VALLIS-NERIA** [ykrank/S1-Next#7]
动态表情基本没有一个能正常显示的

**Comment by ykrank** [comment]
感觉是Glide4的一个bug，升级成4.0之后就出现这一问题了

**Comment by ykrank** [comment]
应该已经解决了 [Fix text span show gif error ](https://github.com/ykrank/S1-Next/commit/2f6171f99ffef4e8cbe9e2123de394f3fa0469a2)
